version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  cooldown:
    default-days: 7
  open-pull-requests-limit: 0
- package-ecosystem: gomod
  directory: /v2
  schedule:
    interval: weekly
  cooldown:
    default-days: 7
    semver-major-days: 30
    semver-minor-days: 7
    semver-patch-days: 5
  open-pull-requests-limit: 0
